version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    resource_class: medium
    pre-steps: # steps to run before steps defined in the job bar
      - run:
          name: Install sshpass
          command: sudo apt-get update; sudo apt-get install sshpass
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            sshpass -p $SSH_PASSWORD ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /var/www/cv.swl.pp.ua && git pull origin master"

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master