version: 2.1

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

jobs:
  deploy:
    machine:
      enabled: true
    resource_class: medium
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:ea:b2:a0:29:11:47:f4:e8:12:56:ed:3b:74:1f:b8"
      - run:
          name: Install sshpass
          command: sudo apt-get update; sudo apt-get install sshpass
      - run:
          name: Deploy Over SSH
          command: |
            export SSHPASS='$SSH_PASSWORD'
            sshpass -e ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /var/www/black-sun.pp.ua && git pull origin master"