version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    resource_class: medium
    steps:
      - run:
          name: Install sshpass
          command: sudo apt-get update; sudo apt-get install sshpass
      - run:
          name: Deploy Over SSH
          command: |
            sshpass -p \"$SSH_PASSWORD\" ssh -p 10001 -l scorpion node0.black-sun.pp.ua "cd /var/www/cv.swl.pp.ua && git pull origin master"

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master