name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update; sudo apt-get install sshpass

      - name: Deploy Over SSH
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          export SSHPASS=$SSH_PASSWORD
          sshpass -e ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_SERVER "cd /var/www/cv.swl.pp.ua && git pull origin master"